--Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
--
--1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
--
--It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
--
--Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
import Data.Set (Set, member,fromList)

main :: IO ()
main =
    print answer

answer :: Int
answer =
    third $ head solutions

third :: (a,b,c) -> c
third (_,_,x) = x

solutions :: [(Int,Int,Int)]
solutions = 
    [ (a,b,a-b) | a <- pentagonals
    , b <- pentagonalsFrom a
    , pentagonal (a-b)
    , pentagonal (a+b)
    ]

pentagonal :: Int -> Bool
pentagonal n =
    n `member` pentagonalsS

-- performance is a bottleneck, use a Set for fast lookups
-- pentagonalL n = n `elem` pentagonals
pentagonalsFrom :: Int -> [Int]
pentagonalsFrom n = 
    takeWhile (<n) pentagonals

maxp :: Int
maxp = 5000

pentagonalsS :: Set Int
pentagonalsS =
    fromList pentagonals

pentagonals :: [Int]
pentagonals =
    map (\n -> (n*(3*n-1))`div`2) [1..maxp]
